name: Test

on:
  push:
    paths:
      - '**.js'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - working-directory: .
        run: bun install
      - working-directory: .
        run: bun run test
